import type { EditorThemeClasses } from "lexical";

export const editorTheme: EditorThemeClasses = {
  paragraph: "mb-3 leading-relaxed text-foreground",
  heading: {
    h1: "text-2xl sm:text-3xl font-bold tracking-tight text-foreground mt-6 mb-3",
    h2: "text-xl sm:text-2xl font-bold tracking-tight text-foreground mt-5 mb-2.5",
    h3: "text-lg sm:text-xl font-semibold tracking-tight text-foreground mt-4 mb-2",
    h4: "text-base sm:text-lg font-semibold text-foreground mt-3 mb-1.5",
    h5: "text-sm font-semibold text-foreground mt-2 mb-1",
    h6: "text-xs font-semibold text-foreground uppercase tracking-wider mt-2 mb-1",
  },
  quote:
    "border-l-4 border-primary/70 bg-muted/40 pl-4 py-2.5 my-4 italic text-muted-foreground rounded-r-md",
  list: {
    nested: {
      listitem: "list-none",
    },
    ol: "list-decimal list-outside ml-6 my-3 space-y-1 text-foreground",
    ul: "list-disc list-outside ml-6 my-3 space-y-1 text-foreground",
    listitem: "leading-relaxed pl-1",
  },
  code: "block bg-muted/80 font-mono text-xs sm:text-sm p-4 my-4 rounded-lg overflow-x-auto border border-border text-foreground leading-normal selection:bg-primary/20",
  codeHighlight: {
    atrule: "text-purple-600 dark:text-purple-400 font-semibold",
    attr: "text-blue-600 dark:text-blue-400",
    boolean: "text-red-500 font-semibold",
    builtin: "text-cyan-600 dark:text-cyan-400",
    cdata: "text-muted-foreground italic",
    char: "text-emerald-600 dark:text-emerald-400",
    class: "text-amber-600 dark:text-amber-400 font-semibold",
    "class-name": "text-amber-600 dark:text-amber-400 font-semibold",
    comment: "text-muted-foreground italic",
    constant: "text-pink-600 dark:text-pink-400",
    deleted: "text-red-500",
    doctype: "text-muted-foreground italic",
    entity: "text-purple-600 dark:text-purple-400",
    function: "text-blue-600 dark:text-blue-400 font-semibold",
    important: "text-red-600 font-bold",
    inserted: "text-emerald-500",
    keyword: "text-purple-600 dark:text-purple-400 font-bold",
    number: "text-orange-500 dark:text-orange-400",
    operator: "text-cyan-600 dark:text-cyan-300",
    prolog: "text-muted-foreground italic",
    property: "text-indigo-600 dark:text-indigo-400",
    punctuation: "text-foreground/70",
    regex: "text-yellow-600 dark:text-yellow-400",
    selector: "text-emerald-600 dark:text-emerald-400",
    string: "text-emerald-600 dark:text-emerald-400",
    symbol: "text-purple-600 dark:text-purple-400",
    tag: "text-rose-600 dark:text-rose-400 font-semibold",
    url: "text-blue-500 underline",
    variable: "text-amber-600 dark:text-amber-400",
  },
  text: {
    bold: "font-bold text-foreground",
    italic: "italic",
    underline: "underline underline-offset-4 decoration-primary/50",
    strikethrough: "line-through text-muted-foreground",
    underlineStrikethrough: "underline line-through decoration-primary/50",
    code: "font-mono text-xs bg-muted px-1.5 py-0.5 rounded border border-border text-primary font-medium",
  },
  link: "text-primary underline font-medium hover:text-primary/80 transition-colors cursor-pointer",
  hr: "my-6 border-t border-border",
};
